name: Sqorm build workflow

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Building Sqorm module
      working-directory: ./src/Sqorm
      run: dotnet build --configuration Release
