name: .NET build workflow

on:
  pull_request:
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    name: building modules
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
